name: flutter_ai_anthropic_llm_provider
description: A Flutter package that provides an implementation of the LlmProvider interface from flutter_ai_toolkit for Anthropic's Claude AI models. Supports streaming responses, chat history management, and multiple Claude models.
version: 1.0.0
homepage: https://github.com/codeium/flutter_ai_anthropic_llm_provider
repository: https://github.com/codeium/flutter_ai_anthropic_llm_provider
issue_tracker: https://github.com/codeium/flutter_ai_anthropic_llm_provider/issues
documentation: https://github.com/codeium/flutter_ai_anthropic_llm_provider#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  flutter_ai_toolkit: ^0.6.8
  anthropic_dart: ^1.0.1
  dio: ^5.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  mockito: ^5.4.0
  test: ^1.24.0

flutter:
